Fix crash with very long account names
Deal with accounts that are longer than the assumed max width.

      File "/home/tbm/src/tbm/beancount2ledger/beancount2ledger/ledger.py", line 163, in Posting
        posting_str = f'  {flag_posting}  {quote_currency(pos_str):>{len_amount}} {quote_currency(price_str)}'
    ValueError: Sign not allowed in string format specifier

Fixes #19