Use latest version of black to work around CI failure
Use the latest version of black because GitHub's CI gets:
    ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/__init__.py)